- name: sudoers
  copy:
    src: sudoers-wheel
    dest: /etc/sudoers.d/99-wheel

- name: skel ssh
  file:
    path: /etc/skel/.ssh
    state: directory
    mode: 0700

- name: sync script
  copy:
    src: sync_ssh_users
    dest: /usr/bin/
    mode: 0755

- name: users-sync cron
  cron:
    cron_file: sync_ssh_users
    user: root
    job: "/usr/bin/sync_ssh_users &>> /var/log/ssh_users.log"

- cronvar:
    name: SSH_TEAMS
    value: "%SSH_TEAMS_TEMPLATE%"
    cron_file: sync_ssh_users

- cronvar:
    name: S3_BUCKET
    value: "%S3_BUCKET_TEMPLATE%"
    cron_file: sync_ssh_users

- name: pull image
  docker_image:
    name: "mergermarket/sync-ssh-users"
